#!/usr/bin/env python3
"""
build_og_cards.py — Open Graph cards for illustrated posts, rendered in CI

Every Post needs a 1200×630 raster for og:image / twitter:image (`image:`).
Travel posts have a photo; illustrated posts used to need a hand-designed SVG
Hero plus a hand-rasterized PNG — the most manual step of publishing. This
script closes that gap for every Post that is not a Trip and has no hand-made
raster yet:

  • no `cover:` and no `image:`   → a templated card is rendered from the front
    matter (title, description, category, subcategory, date, series, tags,
    reading time — computed from the body by reading_time.py, the port of
    _plugins/reading_time.rb, when the front matter has none) in one of the
    two documented cover styles — cream editorial or dark tech — picked by
    the Post's first Category (override with `card_style:`);
  • `cover:` is an SVG, no `image:` → that hand-authored SVG is rasterized as-is
    (same renderer, same fonts), letterboxed onto its own background colour;
  • `image:` already names a real raster (travel photo, hand-made PNG) or the
    Post is a Trip (`location`/`locations`/`countries`) → untouched.

The output is committed as assets/img/posts/<post-slug>.png and `image:` is
filled in (the on-page Hero falls back to `image` when there is no `cover`, so
the generated card also serves as the Hero). A generated file carries a PNG
text chunk naming this script, so a later run can tell it apart from a
hand-made file with the same name: generated cards are re-rendered whenever
their Post changes; anything else is never overwritten.

Rendering: SVG template → CairoSVG → Pillow (RGB, optimized). Fonts are the
site's brand faces (Playfair Display, Source Serif 4, JetBrains Mono), fetched
from google/fonts at a pinned commit into --fonts-dir (gitignored) and exposed
to cairo through a private fontconfig file, so nothing is installed
system-wide and every runner renders the same pixels. A missing font is an
error, never a silent fallback. Decision record: docs/adr/0012.

Usage:
  python3 .github/scripts/build_og_cards.py --download-fonts
  python3 .github/scripts/build_og_cards.py [POST.md ...] [--all] [--dry-run]
      [--out-dir DIR] [--svg-only] [--keep-svg] [--fonts-dir DIR] [--force]

Outputs to $GITHUB_OUTPUT (when set): generated_count, generated_files,
pr_comment.
"""

from __future__ import annotations

import argparse
import io
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

sys.path.insert(0, str(Path(__file__).resolve().parent))
import reading_time  # noqa: E402 — sibling module, port of _plugins/reading_time.rb

try:
    import yaml
except ImportError:  # pragma: no cover
    print("::error::PyYAML is required — python3 -m pip install pyyaml")
    sys.exit(2)

try:
    from PIL import Image, ImageFont, PngImagePlugin
except ImportError:  # pragma: no cover
    print("::error::Pillow is required — python3 -m pip install 'Pillow>=11.2'")
    sys.exit(2)

# ── Config ────────────────────────────────────────────────────────────────────

ROOT       = Path(__file__).resolve().parents[2]
POSTS_DIR  = ROOT / "_posts"
OUT_DIR    = ROOT / "assets" / "img" / "posts"
FONTS_DIR  = ROOT / ".github" / "fonts"

WIDTH, HEIGHT = 1200, 630
SITE_LABEL    = "guilherme.stracini.com.br/blog"

# The PNG text chunk that marks a file as generated by this script. Ownership
# is decided by this marker, not by the file name — a hand-made PNG that happens
# to be named after the post slug (there is one) is never overwritten.
MARKER_KEY   = "Software"
MARKER_VALUE = "guibranco/blog build_og_cards.py"

# Cover style per Category slug. Anything not listed is cream editorial; the
# two dark styles in the repo (Coding architecture cards, Infrastructure
# deploy diagrams) are the "dark tech" family. `card_style:` overrides.
STYLE_BY_CATEGORY = {"coding": "dark", "infrastructure": "dark"}
STYLES = ("cream", "dark")

# Brand fonts, pinned to one google/fonts commit so a runner never picks up a
# silently updated upstream. Variable TTFs: fontconfig exposes their named
# instances, so "Playfair Display:bold" resolves to the real Bold instance.
GOOGLE_FONTS_COMMIT = "809e4d8b8d7e9364a914909bb777679606c178b8"
FONT_FILES = {
    # file name                          : (google/fonts path, family)
    "PlayfairDisplay[wght].ttf"          : ("ofl/playfairdisplay/PlayfairDisplay[wght].ttf",          "Playfair Display"),
    "PlayfairDisplay-Italic[wght].ttf"   : ("ofl/playfairdisplay/PlayfairDisplay-Italic[wght].ttf",   "Playfair Display"),
    "SourceSerif4[opsz,wght].ttf"        : ("ofl/sourceserif4/SourceSerif4[opsz,wght].ttf",           "Source Serif 4"),
    "JetBrainsMono[wght].ttf"            : ("ofl/jetbrainsmono/JetBrainsMono[wght].ttf",              "JetBrains Mono"),
}
FONT_LICENSES = {
    "OFL-PlayfairDisplay.txt": "ofl/playfairdisplay/OFL.txt",
    "OFL-SourceSerif4.txt":    "ofl/sourceserif4/OFL.txt",
    "OFL-JetBrainsMono.txt":   "ofl/jetbrainsmono/OFL.txt",
}
FAMILIES = ("Playfair Display", "Source Serif 4", "JetBrains Mono")

# Typeface roles → (file, named instance for measuring, SVG font-family, weight, style)
DISPLAY        = ("PlayfairDisplay[wght].ttf",        "Regular", "Playfair Display", "400", "normal")
DISPLAY_ITALIC = ("PlayfairDisplay-Italic[wght].ttf", "Italic",  "Playfair Display", "400", "italic")
DISPLAY_BOLD   = ("PlayfairDisplay[wght].ttf",        "Bold",    "Playfair Display", "700", "normal")
BODY           = ("SourceSerif4[opsz,wght].ttf",      "Regular", "Source Serif 4",   "400", "normal")
MONO           = ("JetBrainsMono[wght].ttf",          "Regular", "JetBrains Mono",   "400", "normal")

# Site palette (assets/css/main.css :root) plus the dark-card accents used by
# the hand-made dark covers.
CREAM = {
    "bg": "#f5f0e8", "frame": "#e2dbd0", "ink": "#1a1714", "muted": "#5a534a",
    "light": "#8a8078", "accent": "#2d6a4f", "warm": "#b85c00",
}
DARK = {
    "bg": "#0f0e0c", "grid": "#2a2621", "ink": "#f5f0e8", "muted": "#8a8078",
    "green": "#93c97a", "amber": "#e8a33d",
}

MONTHS = {
    "pt-BR": ["jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez"],
    "en":    ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
}
PART_WORD = {"pt-BR": "Parte", "en": "Part"}

# Measured widths come from Pillow's basic layout (no kerning), cairo's toy
# text API draws the same way — keep a little slack anyway so a line never
# grazes the margin.
MEASURE_SLACK = 1.02

# ── Post model ────────────────────────────────────────────────────────────────

@dataclass
class Post:
    path: Path
    slug: str
    fm: dict
    fm_text: str          # raw front matter block, without the --- fences
    body: str = ""        # everything after the front matter (for the reading-time estimate)

    @property
    def rel(self) -> str:
        return self.path.relative_to(ROOT).as_posix() if self.path.is_relative_to(ROOT) else str(self.path)

    @property
    def owned_url(self) -> str:
        return f"/assets/img/posts/{self.slug}.png"


def post_slug(path: Path) -> str:
    """Jekyll's post slug: the file name without the YYYY-MM-DD- prefix and .md."""
    return re.sub(r"^\d{4}-\d{2}-\d{2}-", "", path.stem)


def read_post(path: Path) -> Post:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---[ \t]*\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|$)", text, re.S)
    if not m:
        raise ValueError(f"{path}: no front matter block")
    fm_text = m.group(1)
    fm = yaml.safe_load(fm_text) or {}
    if not isinstance(fm, dict):
        raise ValueError(f"{path}: front matter is not a mapping")
    return Post(path=path, slug=post_slug(path), fm=fm, fm_text=fm_text, body=text[m.end():])


def as_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        return [str(v).strip() for v in value if v is not None and str(v).strip()]
    return [str(value).strip()] if str(value).strip() else []


def is_trip(fm: dict) -> bool:
    return any(k in fm for k in ("location", "locations", "countries"))


def local_asset(value) -> Path | None:
    """Repo path for a site-relative front matter value; None for URLs/empty."""
    value = str(value or "").strip()
    if not value or value.startswith(("http://", "https://")):
        return None
    return ROOT / value.lstrip("/")


def is_generated(png: Path) -> bool:
    if not png.exists():
        return False
    try:
        with Image.open(png) as im:
            return im.info.get(MARKER_KEY) == MARKER_VALUE
    except Exception:
        return False


@dataclass
class Plan:
    post: Post
    action: str                    # "card" | "cover" | "skip"
    reason: str = ""
    cover: Path | None = None
    style: str = ""


def classify(post: Post, force: bool, preview: bool = False) -> Plan:
    """Decide what to do with a post.

    `preview` ignores the "already has an image" / Trip rules — it renders
    what the generator *would* produce for any post, into a scratch
    directory, without writing anything to the repo.
    """
    fm = post.fm
    if not preview:
        if is_trip(fm):
            return Plan(post, "skip", "Trip — keeps its photo")

        out_png = OUT_DIR / f"{post.slug}.png"
        image = str(fm.get("image") or "").strip()
        if image:
            if image != post.owned_url:
                return Plan(post, "skip", f"`image:` already set ({image})")
            if not is_generated(out_png) and out_png.exists():
                return Plan(post, "skip", f"`image:` names a hand-made file ({image})")
        elif out_png.exists() and not is_generated(out_png) and not force:
            return Plan(post, "skip", f"{out_png.relative_to(ROOT).as_posix()} exists and was not generated here — rename it or pass --force")

    cover = str(fm.get("cover") or "").strip()
    if cover:
        cover_path = local_asset(cover)
        if cover_path is None:
            return Plan(post, "skip", f"`cover:` is external ({cover})")
        if cover_path.suffix.lower() != ".svg":
            return Plan(post, "skip", f"`cover:` is already a raster ({cover}) — point `image:` at it")
        if not cover_path.exists():
            return Plan(post, "skip", f"`cover:` file missing ({cover})")
        return Plan(post, "cover", cover=cover_path)

    style = str(fm.get("card_style") or "").strip().lower()
    if style and style not in STYLES:
        raise ValueError(f"{post.rel}: card_style must be one of {'/'.join(STYLES)}, got '{style}'")
    if not style:
        first_cat = (as_list(fm.get("categories")) or [""])[0]
        style = STYLE_BY_CATEGORY.get(slugify(first_cat), "cream")
    return Plan(post, "card", style=style)


def slugify(text: str) -> str:
    """Latin slugify matching Jekyll's `slugify: 'latin'` (same as audit_blog.py)."""
    replacements = {
        "ã": "a", "â": "a", "á": "a", "à": "a", "ê": "e", "é": "e", "è": "e",
        "í": "i", "ì": "i", "ô": "o", "õ": "o", "ó": "o", "ú": "u", "ü": "u", "ç": "c",
    }
    s = text.lower()
    for src, dst in replacements.items():
        s = s.replace(src, dst)
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s.strip())
    return re.sub(r"-+", "-", s).strip("-")


# ── Fonts ─────────────────────────────────────────────────────────────────────

def raw_url(repo_path: str) -> str:
    return (f"https://raw.githubusercontent.com/google/fonts/{GOOGLE_FONTS_COMMIT}/"
            + urllib.parse.quote(repo_path))


def download_fonts(fonts_dir: Path) -> None:
    fonts_dir.mkdir(parents=True, exist_ok=True)
    wanted = {name: path for name, (path, _) in FONT_FILES.items()}
    wanted.update(FONT_LICENSES)
    for name, repo_path in wanted.items():
        target = fonts_dir / name
        if target.exists() and target.stat().st_size > 0:
            print(f"  ✓ {name} (cached)")
            continue
        url = raw_url(repo_path)
        try:
            with urllib.request.urlopen(url, timeout=60) as resp:
                data = resp.read()
        except (urllib.error.URLError, OSError) as e:
            raise SystemExit(
                f"::error::Could not download {url}: {e}\n"
                f"Download it manually into {fonts_dir} (e.g. `gh api "
                f"repos/google/fonts/contents/{repo_path}?ref={GOOGLE_FONTS_COMMIT} "
                f"-H 'Accept: application/vnd.github.raw' > '{target}'`)."
            )
        target.write_bytes(data)
        print(f"  ⬇ {name} ({len(data) // 1024} KB)")


def missing_fonts(fonts_dir: Path) -> list[str]:
    return [name for name in FONT_FILES if not (fonts_dir / name).exists()]


def configure_fontconfig(fonts_dir: Path) -> Path:
    """Point fontconfig (and therefore cairo) at the vendored fonts only.

    A private fonts.conf keeps the render independent from whatever the runner
    has installed; the system config is still included as a fallback for
    glyphs the brand fonts lack. Must run before cairo is first used.
    """
    cache = fonts_dir / ".fontconfig-cache"
    cache.mkdir(parents=True, exist_ok=True)
    conf = fonts_dir / "fonts.conf"
    conf.write_text(
        '<?xml version="1.0"?>\n'
        '<!DOCTYPE fontconfig SYSTEM "fonts.dtd">\n'
        "<fontconfig>\n"
        f"  <dir>{xml_escape(str(fonts_dir.resolve()))}</dir>\n"
        f"  <cachedir>{xml_escape(str(cache.resolve()))}</cachedir>\n"
        '  <include ignore_missing="yes">/etc/fonts/fonts.conf</include>\n'
        "</fontconfig>\n",
        encoding="utf-8",
    )
    os.environ["FONTCONFIG_FILE"] = str(conf.resolve())
    return conf


def check_fontconfig(fonts_dir: Path) -> None:
    """Fail loudly if cairo would substitute a brand font (fc-match is what it uses)."""
    if shutil.which("fc-match") is None:
        print("::warning::fc-match not found — cannot verify font resolution; cairo may substitute fonts")
        return
    problems = []
    for family in FAMILIES:
        for style in ("regular", "bold", "italic"):
            if style != "regular" and family != "Playfair Display":
                continue
            query = f"{family}:{style}"
            out = subprocess.run(
                ["fc-match", "-f", "%{family}|%{style}|%{file}", query],
                capture_output=True, text=True, env=os.environ,
            ).stdout.strip()
            matched_families, _, rest = out.partition("|")
            matched_style, _, matched_file = rest.partition("|")
            if family not in matched_families.split(",") or not matched_file.startswith(str(fonts_dir.resolve())):
                problems.append(f"{query} → {out or '(no match)'}")
            else:
                print(f"  ✓ {query:28} → {Path(matched_file).name} ({matched_style.split(',')[0]})")
    if problems:
        raise SystemExit("::error::Font resolution failed, refusing to render with substitutes:\n  "
                         + "\n  ".join(problems))


class Measurer:
    """Text widths via Pillow on the same TTFs cairo renders with."""

    def __init__(self, fonts_dir: Path):
        self.fonts_dir = fonts_dir
        self._cache: dict[tuple, ImageFont.FreeTypeFont] = {}

    def _font(self, face: tuple, size: float) -> ImageFont.FreeTypeFont:
        file, instance = face[0], face[1]
        key = (file, instance, round(size, 2))
        font = self._cache.get(key)
        if font is None:
            font = ImageFont.truetype(str(self.fonts_dir / file), size=size)
            try:
                font.set_variation_by_name(instance)
            except Exception:
                pass  # static face or FreeType without variation support — default instance
            self._cache[key] = font
        return font

    def width(self, text: str, face: tuple, size: float, letter_spacing: float = 0) -> float:
        if not text:
            return 0.0
        w = self._font(face, size).getlength(text) * MEASURE_SLACK
        return w + letter_spacing * max(len(text) - 1, 0)

    def wrap(self, text: str, face: tuple, size: float, max_width: float) -> list[str]:
        """Greedy word wrap. A single over-long word gets its own line."""
        words = text.split()
        lines: list[str] = []
        current = ""
        for word in words:
            candidate = f"{current} {word}".strip()
            if current and self.width(candidate, face, size) > max_width:
                lines.append(current)
                current = word
            else:
                current = candidate
        if current:
            lines.append(current)
        return lines

    def truncate(self, lines: list[str], max_lines: int, face: tuple, size: float, max_width: float) -> list[str]:
        """Keep at most max_lines, ending the last kept line with an ellipsis."""
        if len(lines) <= max_lines:
            return lines
        kept = lines[:max_lines]
        last = kept[-1].rstrip(" ,;:—–-")
        while last and self.width(last + "…", face, size) > max_width:
            last = last.rsplit(" ", 1)[0] if " " in last else last[:-1]
            last = last.rstrip(" ,;:—–-")
        kept[-1] = last + "…"
        return kept


# ── Card content ──────────────────────────────────────────────────────────────

@dataclass
class Content:
    title_head: str
    title_kicker: str
    description: str
    eyebrow: str          # "Career · Case Studies"
    series: str           # "Postmortem de carreira · Parte 2" or ""
    date_label: str       # "10 set 2026" / "Sep 10, 2026"
    reading: str          # "10 min" or ""
    tags: list[str] = field(default_factory=list)


def split_title(title: str) -> tuple[str, str]:
    """Head + kicker at the first ': ' or spaced dash; the kicker becomes the
    italic/green second thought the hand-made cards use."""
    for sep in (": ", " — ", " – "):
        if sep in title:
            head, kicker = title.split(sep, 1)
            head, kicker = head.strip(), kicker.strip()
            if head and kicker:
                return head, kicker
    return title.strip(), ""


def category_label(fm: dict) -> str:
    cats = as_list(fm.get("categories"))
    first = cats[0] if cats else ""
    sub = ""
    for item in as_list(fm.get("subcategories")):
        if "/" in item:
            parent, child = (s.strip() for s in item.split("/", 1))
            if parent == first or not sub:
                sub = child
                if parent == first:
                    break
    if not sub:
        sub = str(fm.get("subcategory") or "").strip()
    return " · ".join(p for p in (first, sub) if p)


def format_date(value, lang: str) -> str:
    if isinstance(value, datetime):
        value = value.date()
    if isinstance(value, str):
        try:
            value = datetime.strptime(value[:10], "%Y-%m-%d").date()
        except ValueError:
            return value
    if not isinstance(value, date):
        return ""
    months = MONTHS.get(lang, MONTHS["en"])
    if lang == "pt-BR":
        return f"{value.day:02d} {months[value.month - 1]} {value.year}"
    return f"{months[value.month - 1]} {value.day}, {value.year}"


def build_content(post: Post) -> Content:
    fm = post.fm
    lang = str(fm.get("lang") or "pt-BR")
    head, kicker = split_title(str(fm.get("title") or post.slug))
    series = ""
    series_title = str(fm.get("series_title") or "").strip()
    if not series_title and fm.get("series"):
        series_title = str(fm["series"]).replace("-", " ").strip()
    if series_title:
        part = fm.get("series_part")
        series = series_title if part in (None, "") else f"{series_title} · {PART_WORD.get(lang, 'Part')} {part}"
    # A manual `reading_time:` wins; otherwise the same estimate the Jekyll
    # plugin makes at build time, so the card matches the page (ADR-0013).
    reading = fm.get("reading_time")
    if reading in (None, ""):
        reading = reading_time.estimate(post.body, reading_time.load_config())
    return Content(
        title_head=head,
        title_kicker=kicker,
        description=" ".join(str(fm.get("description") or "").split()),
        eyebrow=category_label(fm),
        series=series,
        date_label=format_date(fm.get("date"), lang),
        reading=f"{reading} min" if reading not in (None, "") else "",
        tags=as_list(fm.get("tags")),
    )


# ── SVG templates ─────────────────────────────────────────────────────────────

def attr(value: str) -> str:
    return xml_escape(value, {'"': "&quot;"})


def text_el(x: float, y: float, text: str, face: tuple, size: float, fill: str,
            anchor: str = "start", letter_spacing: float = 0, extra: str = "") -> str:
    _, _, family, weight, style = face
    parts = [
        f'<text x="{x:g}" y="{y:g}"',
        f'font-family="{family}, Georgia, serif"' if family != "JetBrains Mono" else f'font-family="{family}, monospace"',
        f'font-size="{size:g}"',
    ]
    if weight != "400":
        parts.append(f'font-weight="{weight}"')
    if style != "normal":
        parts.append(f'font-style="{style}"')
    if anchor != "start":
        parts.append(f'text-anchor="{anchor}"')
    if letter_spacing:
        parts.append(f'letter-spacing="{letter_spacing:g}"')
    parts.append(f'fill="{fill}"')
    if extra:
        parts.append(extra)
    return " ".join(parts) + f">{xml_escape(text)}</text>"


@dataclass
class TitleLayout:
    size: float
    head_lines: list[str]
    kicker_size: float
    kicker_lines: list[str]
    desc_lines: list[str]
    bottom: float          # baseline of the last description line


def layout_text(m: Measurer, c: Content, *, head_face: tuple, kicker_face: tuple,
                sizes: tuple[float, ...], line_height: float, kicker_ratio: float,
                kicker_line_height: float, max_width: float, max_head_lines: int,
                desc_size: float, desc_line_height: float, desc_max_lines: int,
                title_top: float, rule_gap: float, desc_gap: float, limit: float) -> tuple[TitleLayout, float]:
    """Try title sizes from largest down until everything fits above `limit`.

    Returns the layout and the y of the rule between title and description.
    Falls back to fewer description lines, then to the smallest size.
    """
    best = None
    for size in sizes:
        head_lines = m.wrap(c.title_head, head_face, size, max_width)
        if len(head_lines) > max_head_lines:
            continue
        kicker_size = max(round(size * kicker_ratio), 28)
        kicker_lines = m.wrap(c.title_kicker, kicker_face, kicker_size, max_width) if c.title_kicker else []
        if len(kicker_lines) > 2:
            continue
        y = title_top + (len(head_lines) - 1) * size * line_height
        if kicker_lines:
            y += size * 0.42 + kicker_size + (len(kicker_lines) - 1) * kicker_size * kicker_line_height
        rule_y = y + rule_gap
        desc_all = m.wrap(c.description, BODY, desc_size, max_width) if c.description else []
        for max_lines in range(desc_max_lines, 0, -1):
            desc_lines = m.truncate(desc_all, max_lines, BODY, desc_size, max_width)
            bottom = rule_y + desc_gap + (len(desc_lines) - 1) * desc_line_height if desc_lines else rule_y
            candidate = (TitleLayout(size, head_lines, kicker_size, kicker_lines, desc_lines, bottom), rule_y)
            if bottom <= limit:
                return candidate
            if best is None:
                best = candidate
        if best is None:
            best = candidate
    if best is None:  # every size wrapped the head too long — take the smallest and let it run
        size = sizes[-1]
        head_lines = m.wrap(c.title_head, head_face, size, max_width)[:max_head_lines + 1]
        kicker_size = max(round(size * kicker_ratio), 28)
        kicker_lines = m.wrap(c.title_kicker, kicker_face, kicker_size, max_width)[:2] if c.title_kicker else []
        y = title_top + (len(head_lines) - 1) * size * line_height
        if kicker_lines:
            y += size * 0.42 + kicker_size + (len(kicker_lines) - 1) * kicker_size * kicker_line_height
        rule_y = y + rule_gap
        desc_lines = m.truncate(m.wrap(c.description, BODY, desc_size, max_width), 1, BODY, desc_size, max_width) if c.description else []
        best = (TitleLayout(size, head_lines, kicker_size, kicker_lines, desc_lines, rule_y + desc_gap if desc_lines else rule_y), rule_y)
    return best


def render_cream(m: Measurer, c: Content, aria: str) -> str:
    p = CREAM
    x0, x1 = 80, 1120
    width = x1 - x0
    layout, rule_y = layout_text(
        m, c, head_face=DISPLAY, kicker_face=DISPLAY_ITALIC,
        sizes=(72, 64, 58, 52, 46), line_height=1.14, kicker_ratio=0.64, kicker_line_height=1.18,
        max_width=width, max_head_lines=3, desc_size=26, desc_line_height=38, desc_max_lines=3,
        title_top=204, rule_gap=34, desc_gap=48, limit=508,
    )
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="{WIDTH}" height="{HEIGHT}" role="img" aria-label="{attr(aria)}">',
        f'  <title>{xml_escape(aria)}</title>',
        f'  <rect width="{WIDTH}" height="{HEIGHT}" fill="{p["bg"]}"/>',
        f'  <rect x="32" y="32" width="{WIDTH - 64}" height="{HEIGHT - 64}" fill="none" stroke="{p["frame"]}" stroke-width="1.5"/>',
        "  " + text_el(x0, 110, c.eyebrow.upper(), MONO, 19, p["warm"], letter_spacing=4.2),
        f'  <line x1="{x0}" y1="126" x2="{x0 + 84}" y2="126" stroke="{p["warm"]}" stroke-width="3"/>',
    ]
    if c.series:
        out.append("  " + text_el(x1, 110, c.series.upper(), MONO, 15, p["light"], anchor="end", letter_spacing=2.4))

    # A short card would leave a void above the footer — nudge the block down
    # by up to 80px so the empty space is shared between top and bottom.
    shift = min(max((508 - layout.bottom) / 2, 0), 80)
    rule_y += shift
    y = 204.0 + shift
    for i, line in enumerate(layout.head_lines):
        y = 204 + shift + i * layout.size * 1.14
        out.append("  " + text_el(x0, y, line, DISPLAY, layout.size, p["ink"]))
    if layout.kicker_lines:
        y += layout.size * 0.42 + layout.kicker_size
        for i, line in enumerate(layout.kicker_lines):
            yy = y + i * layout.kicker_size * 1.18
            out.append("  " + text_el(x0, yy, line, DISPLAY_ITALIC, layout.kicker_size, p["accent"]))

    out.append(f'  <line x1="{x0}" y1="{rule_y:g}" x2="{x0 + 360}" y2="{rule_y:g}" stroke="{p["frame"]}" stroke-width="1"/>')
    for i, line in enumerate(layout.desc_lines):
        out.append("  " + text_el(x0, rule_y + 48 + i * 38, line, BODY, 26, p["muted"]))

    footer_right = " · ".join(s for s in (c.date_label, c.reading) if s).upper()
    out += [
        f'  <line x1="{x0}" y1="546" x2="{x1}" y2="546" stroke="{p["frame"]}" stroke-width="1"/>',
        "  " + text_el(x0, 578, SITE_LABEL, MONO, 15, p["light"], letter_spacing=1.6),
    ]
    if footer_right:
        out.append("  " + text_el(x1, 578, footer_right, MONO, 15, p["light"], anchor="end", letter_spacing=1.6))
    out.append("</svg>")
    return "\n".join(out) + "\n"


def render_dark(m: Measurer, c: Content, aria: str) -> str:
    p = DARK
    x0, x1 = 80, 1120
    width = x1 - x0
    has_tags = bool(c.tags)
    layout, rule_y = layout_text(
        m, c, head_face=DISPLAY_BOLD, kicker_face=DISPLAY_BOLD,
        sizes=(82, 72, 64, 56, 50), line_height=1.08, kicker_ratio=0.72, kicker_line_height=1.12,
        max_width=width, max_head_lines=3, desc_size=26, desc_line_height=38, desc_max_lines=2,
        title_top=214, rule_gap=36, desc_gap=54, limit=466 if has_tags else 516,
    )
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="{WIDTH}" height="{HEIGHT}" role="img" aria-label="{attr(aria)}">',
        f'  <title>{xml_escape(aria)}</title>',
        "  <defs>",
        '    <radialGradient id="glow" cx="0.12" cy="0.12" r="0.7">',
        f'      <stop offset="0%" stop-color="{p["green"]}" stop-opacity="0.13"/>',
        f'      <stop offset="100%" stop-color="{p["green"]}" stop-opacity="0"/>',
        "    </radialGradient>",
        "  </defs>",
        f'  <rect width="{WIDTH}" height="{HEIGHT}" fill="{p["bg"]}"/>',
        f'  <g stroke="{p["grid"]}" stroke-width="0.9" opacity="0.45">',
    ]
    for gx in range(60, WIDTH, 60):
        out.append(f'    <line x1="{gx}" y1="0" x2="{gx}" y2="{HEIGHT}"/>')
    for gy in range(60, HEIGHT, 60):
        out.append(f'    <line x1="0" y1="{gy}" x2="{WIDTH}" y2="{gy}"/>')
    out += [
        "  </g>",
        f'  <rect width="{WIDTH}" height="{HEIGHT}" fill="url(#glow)"/>',
        "  " + text_el(x0, 86, "// " + c.eyebrow.lower(), MONO, 20, p["green"], letter_spacing=2.8),
    ]
    top_right = c.series.upper() if c.series else ""
    if top_right:
        out.append("  " + text_el(x1, 86, top_right, MONO, 20, p["amber"], anchor="end", letter_spacing=2.8))
    out.append(f'  <line x1="{x0}" y1="110" x2="{x1}" y2="110" stroke="{p["grid"]}" stroke-width="1.5"/>')

    limit = 466 if has_tags else 516
    shift = min(max((limit - layout.bottom) / 2, 0), 48)
    rule_y += shift
    y = 214.0 + shift
    for i, line in enumerate(layout.head_lines):
        y = 214 + shift + i * layout.size * 1.08
        out.append("  " + text_el(x0, y, line, DISPLAY_BOLD, layout.size, p["ink"]))
    if layout.kicker_lines:
        y += layout.size * 0.42 + layout.kicker_size
        for i, line in enumerate(layout.kicker_lines):
            yy = y + i * layout.kicker_size * 1.12
            out.append("  " + text_el(x0, yy, line, DISPLAY_BOLD, layout.kicker_size, p["green"]))

    out.append(f'  <rect x="{x0}" y="{rule_y - 4:g}" width="100" height="5" fill="{p["amber"]}"/>')
    for i, line in enumerate(layout.desc_lines):
        out.append("  " + text_el(x0, rule_y + 54 + i * 38, line, BODY, 26, p["muted"]))

    if has_tags:
        chip_y, chip_h, pad, gap, size = 496, 36, 16, 12, 17
        x = float(x0)
        for tag in c.tags[:10]:
            w = m.width(tag, MONO, size) + 2 * pad
            if x + w > x1:
                break
            out.append(f'  <rect x="{x:g}" y="{chip_y}" width="{w:g}" height="{chip_h}" rx="3" fill="none" stroke="{p["grid"]}" stroke-width="1"/>')
            out.append("  " + text_el(x + w / 2, chip_y + 24, tag, MONO, size, p["muted"], anchor="middle"))
            x += w + gap

    footer_right = " · ".join(s for s in (c.date_label, c.reading) if s).upper()
    out += [
        f'  <line x1="{x0}" y1="556" x2="{x1}" y2="556" stroke="{p["grid"]}" stroke-width="1.5"/>',
        f'  <circle cx="{x0}" cy="556" r="3" fill="{p["green"]}"/>',
        "  " + text_el(x0, 590, SITE_LABEL, MONO, 15, p["muted"], letter_spacing=1.6),
    ]
    if footer_right:
        out.append("  " + text_el(x1, 590, footer_right, MONO, 15, p["amber"], anchor="end", letter_spacing=1.6))
    out.append("</svg>")
    return "\n".join(out) + "\n"


RENDERERS = {"cream": render_cream, "dark": render_dark}


# ── Rasterization ─────────────────────────────────────────────────────────────

def _cairosvg():
    try:
        import cairosvg  # noqa: WPS433 — imported late so FONTCONFIG_FILE is set first
    except (ImportError, OSError) as e:
        raise SystemExit(f"::error::CairoSVG is required to rasterize (python3 -m pip install cairosvg; needs libcairo2): {e}")
    return cairosvg


def save_png(png_bytes: bytes, out: Path) -> None:
    """Flatten to RGB, tag as generated, optimize. Deterministic for equal input."""
    info = PngImagePlugin.PngInfo()
    info.add_text(MARKER_KEY, MARKER_VALUE)
    with Image.open(io.BytesIO(png_bytes)) as im:
        rgb = im.convert("RGB")
        if rgb.size != (WIDTH, HEIGHT):
            rgb = rgb.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)
        out.parent.mkdir(parents=True, exist_ok=True)
        tmp = out.with_name(out.name + ".tmp")
        rgb.save(tmp, format="PNG", optimize=True, pnginfo=info)
    os.replace(tmp, out)


def rasterize_svg_text(svg: str, out: Path) -> None:
    png = _cairosvg().svg2png(bytestring=svg.encode("utf-8"), output_width=WIDTH, output_height=HEIGHT)
    save_png(png, out)


def svg_background(svg_text: str) -> str:
    """Best guess at a hand-made cover's background: its first filled rect, else
    the first gradient stop, else the site's cream surface."""
    m = re.search(r"<rect[^>]*\bfill=\"(#[0-9a-fA-F]{3,8})\"", svg_text)
    if m:
        return m.group(1)
    m = re.search(r"stop-color=\"(#[0-9a-fA-F]{3,8})\"", svg_text)
    if m:
        return m.group(1)
    return CREAM["bg"]


def rasterize_cover(cover: Path, out: Path) -> None:
    """Hand-authored SVG → 1200×630, scaled uniformly (viewBox `meet`) and
    letterboxed on its own background colour when the aspect differs."""
    svg_text = cover.read_text(encoding="utf-8")
    png = _cairosvg().svg2png(
        bytestring=svg_text.encode("utf-8"), url=str(cover),
        output_width=WIDTH, output_height=HEIGHT, background_color=svg_background(svg_text),
    )
    save_png(png, out)


# ── Front matter update ───────────────────────────────────────────────────────

def set_image_field(post: Post, value: str) -> bool:
    """Write `image: <value>` into the post's front matter, textually, keeping
    everything else byte-for-byte. Returns True when the file changed."""
    # newline="" on both ends so the file's own line endings survive untouched
    text = post.path.read_text(encoding="utf-8", newline="")
    m = re.match(r"^(---[ \t]*\r?\n)(.*?)(\r?\n---[ \t]*(?:\r?\n|$))", text, re.S)
    if not m:
        raise ValueError(f"{post.rel}: no front matter block")
    head, block, tail = m.group(1), m.group(2), m.group(3)
    newline = "\r\n" if "\r\n" in head else "\n"
    lines = block.split(newline)
    line = f"image: {value}"

    for i, existing in enumerate(lines):
        if re.match(r"^image:\s*", existing):
            if existing.strip() == line:
                return False
            lines[i] = line
            break
    else:
        anchor = None
        for i, existing in enumerate(lines):
            if re.match(r"^(cover|reading_time):\s*\S", existing):
                anchor = i
        if anchor is None:
            lines.append(line)
        else:
            lines.insert(anchor + 1, line)

    post.path.write_text(head + newline.join(lines) + tail + text[m.end():], encoding="utf-8", newline="")
    return True


# ── Main ──────────────────────────────────────────────────────────────────────

def write_output(key: str, value: str) -> None:
    github_output = os.environ.get("GITHUB_OUTPUT")
    if not github_output:
        return
    with open(github_output, "a", encoding="utf-8") as f:
        if "\n" in value:
            delimiter = "EOF_" + key.upper()
            f.write(f"{key}<<{delimiter}\n{value}\n{delimiter}\n")
        else:
            f.write(f"{key}={value}\n")


def build_pr_comment(results: list[tuple[Plan, str]]) -> str:
    lines = [
        "## 🖼️ Open Graph cards generated\n",
        f"**{len(results)} card(s)** were rendered from the front matter and committed to this "
        "branch, and `image:` was filled in. Trips and posts that already had a raster `image:` "
        "were left alone.\n",
        "| Post | Card | How |",
        "|---|---|---|",
    ]
    for plan, out_rel in results:
        how = f"templated · {plan.style}" if plan.action == "card" else f"rasterized `{plan.cover.relative_to(ROOT).as_posix()}`"
        lines.append(f"| `{plan.post.rel}` | `{out_rel}` | {how} |")
    lines += [
        "",
        "To change a card, edit the post (title/description/`card_style`) — it is re-rendered on the next push. "
        "To hand-design it instead, replace the PNG (or add a `cover:` SVG) and drop the `Software` marker.",
        "",
        "---",
        "> _Committed by `github-actions[bot]` · workflow: `og-cards.yml` · "
        "[ADR-0012](docs/adr/0012-og-cards-generated-in-ci-from-front-matter.md)_",
    ]
    return "\n".join(lines)


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):  # Windows consoles default to cp1252
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description="Render Open Graph cards for posts without a hand-made raster.")
    parser.add_argument("posts", nargs="*", help="post files to process (default: every post in _posts/)")
    parser.add_argument("--all", action="store_true", help="explicitly process every post (same as no POST args)")
    parser.add_argument("--download-fonts", action="store_true", help="fetch the pinned brand fonts into --fonts-dir and exit")
    parser.add_argument("--fonts-dir", type=Path, default=FONTS_DIR, help=f"where the brand TTFs live (default {FONTS_DIR.relative_to(ROOT).as_posix()}/)")
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR, help="where to write PNGs (default assets/img/posts/)")
    parser.add_argument("--dry-run", action="store_true", help="report what would be rendered, touch nothing")
    parser.add_argument("--preview", action="store_true",
                        help="render the given posts even if they already have an image (or are Trips) into --out-dir, never touching the repo")
    parser.add_argument("--svg-only", action="store_true", help="write the SVG next to the PNG target and skip rasterizing (no cairo needed)")
    parser.add_argument("--keep-svg", action="store_true", help="also write the rendered SVG next to the PNG")
    parser.add_argument("--no-front-matter", action="store_true", help="do not write `image:` into the posts")
    parser.add_argument("--force", action="store_true", help="overwrite a same-named PNG that was not generated here")
    args = parser.parse_args()

    fonts_dir: Path = args.fonts_dir if args.fonts_dir.is_absolute() else (ROOT / args.fonts_dir)
    out_dir: Path = args.out_dir if args.out_dir.is_absolute() else (ROOT / args.out_dir)
    if args.preview:
        args.no_front_matter = True
        if out_dir.resolve() == OUT_DIR.resolve():
            raise SystemExit("::error::--preview needs an --out-dir outside assets/img/posts/ — it must never overwrite real cards")

    if args.download_fonts:
        print(f"Fetching brand fonts (google/fonts @ {GOOGLE_FONTS_COMMIT[:12]}) into {fonts_dir}")
        download_fonts(fonts_dir)
        return

    if args.posts:
        paths = []
        for p in args.posts:
            path = Path(p)
            if not path.is_absolute() and not path.exists():
                path = ROOT / path  # repo-relative, as the workflow passes them
            if not path.exists():
                print(f"⚠ File not found, skipping: {p}")
                continue
            paths.append(path.resolve())
    else:
        paths = sorted(POSTS_DIR.glob("*.md"))

    plans: list[Plan] = []
    for path in paths:
        try:
            plans.append(classify(read_post(path), args.force, args.preview))
        except (ValueError, yaml.YAMLError) as e:
            rel = path.relative_to(ROOT).as_posix() if path.is_relative_to(ROOT) else str(path)
            raise SystemExit(f"::error file={rel}::{e}")

    todo = [p for p in plans if p.action != "skip"]
    print(f"\n📄 {len(plans)} post(s) scanned — {len(todo)} to render, {len(plans) - len(todo)} skipped\n")
    for plan in plans:
        if plan.action == "skip":
            print(f"  · {plan.post.rel}: {plan.reason}")
    if not todo:
        print("\nNothing to render.")
        write_output("generated_count", "0")
        write_output("generated_files", "")
        write_output("pr_comment", "")
        return

    missing = missing_fonts(fonts_dir)
    if missing:
        raise SystemExit(
            f"::error::Missing brand fonts in {fonts_dir}: {', '.join(missing)} — "
            "run `python3 .github/scripts/build_og_cards.py --download-fonts` first"
        )
    measurer = Measurer(fonts_dir)
    if not args.svg_only and not args.dry_run:
        configure_fontconfig(fonts_dir)
        check_fontconfig(fonts_dir)

    results: list[tuple[Plan, str]] = []
    generated_files: list[str] = []
    for plan in todo:
        post = plan.post
        out_png = out_dir / f"{post.slug}.png"
        out_rel = out_png.relative_to(ROOT).as_posix() if out_png.is_relative_to(ROOT) else str(out_png)
        what = f"templated card ({plan.style})" if plan.action == "card" else f"rasterized cover {plan.cover.relative_to(ROOT).as_posix()}"
        if args.dry_run:
            print(f"  ▶ would render {what} → {out_rel}")
            continue

        if plan.action == "card":
            content = build_content(post)
            svg = RENDERERS[plan.style](measurer, content, str(post.fm.get("title") or post.slug))
            if args.svg_only or args.keep_svg:
                svg_path = out_png.with_suffix(".svg")
                svg_path.parent.mkdir(parents=True, exist_ok=True)
                svg_path.write_text(svg, encoding="utf-8")
                print(f"  ✎ {svg_path.relative_to(ROOT).as_posix() if svg_path.is_relative_to(ROOT) else svg_path}")
            if not args.svg_only:
                rasterize_svg_text(svg, out_png)
        else:
            if args.svg_only:
                print(f"  · {post.rel}: cover rasterization needs cairo — skipped under --svg-only")
                continue
            rasterize_cover(plan.cover, out_png)

        if not args.svg_only:
            size_kb = out_png.stat().st_size // 1024
            print(f"  🖼️  {out_rel} ({size_kb} KB) ← {what}")
            generated_files.append(out_rel)
            results.append((plan, out_rel))
            if not args.no_front_matter and out_png.parent == OUT_DIR:
                if set_image_field(post, post.owned_url):
                    print(f"     ↳ image: {post.owned_url} written to {post.rel}")

    print(f"\n{len(results)} card(s) generated.")
    write_output("generated_count", str(len(results)))
    write_output("generated_files", " ".join(generated_files))
    write_output("pr_comment", build_pr_comment(results) if results else "")


if __name__ == "__main__":
    main()
